# Documentation: http://docs.travis-ci.com/user/languages/julia/

language: julia

# Linux builds are ubuntu so gcl is used by default and
# everything fails miserably
os:
  - osx

julia:
  - 1.0.5
  - 1.2.0

notifications:
  email: false

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then brew update                    ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then brew install maxima            ; fi

after_success:
  # push coverage results to Coveralls
  - julia -e 'using Pkg; cd(Pkg.dir("Maxima")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'using Pkg; cd(Pkg.dir("Maxima")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'

jobs:
  include:
    - stage: "Documentation"
      julia: 1.0.5
      os: osx
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
